# Generated by scripts/export_public.py. Runs the HeyLead MCP server over stdio.
FROM python:3.12-slim
RUN pip install --no-cache-dir heylead==0.10.402
RUN useradd --create-home heylead
USER heylead
WORKDIR /home/heylead
ENTRYPOINT ["heylead"]
